Update to xen 4.14 and go 1.16
Gandi/xenlight_exporter pull request #1
Opened 2021-06-17 05:36 UTC by cavus700

2021-06-21 08:07 UTC, diconico07 requested changes
First, thanks for the quite complete PR,
I however see many changes unrelated to go1.16 and xen4.14 upgrade, can you split this lone commit in multiple commits for every change, I see those at least (I let you order them as you want):
 - Docker image building
 - Upgrade to go 1.16
 - Upgrade to Xen 4.14
 - Split into two packages

Except the need to split in multiple commits and my slight issue with the choice of docker's base image, it looks good to me.

2021-06-21 08:07 UTC, diconico07 commented on Dockerfile
> +FROM fedora:34
I'd rather use an official golang image to benefit from golang version in tag (like eg `golang:1.16-alpine3.13`, I chose an alpine 3.13 one here as it also have xen 4.14 in its repository, but I'm not allergic to other flavors :smile: )

2021-06-21 09:21 UTC, cavus700 commented on Dockerfile
> +FROM fedora:34
Thank you for the interest in my PR :) I split the commits in three. It was not so easy to make seperate commits out of the go and xen update so I hope it is ok to have only one for it.
I would also like to use an golang/alpine container but I could not make it compile the project. I always got some cgo errors related to xen files. Maybe I just missed an apk package or something is different there with the xen-dev package.

2021-06-21 11:21 UTC, diconico07 commented on Dockerfile
> +FROM fedora:34
Ok, fine with me then as it seems there is no official golang image that fits.

2021-06-21 11:21 UTC, diconico07 approved these changes

2021-06-21 13:51 UTC, nlewo requested changes

2021-06-21 13:51 UTC, nlewo commented on go.mod
> +module github.com/xenlight_exporter
```suggestion
module github.com/gandi/xenlight_exporter
```

2021-06-21 13:51 UTC, nlewo commented on main.go
> +	collect "github.com/xenlight_exporter/pkg/collectors"
```suggestion
	collect "github.com/gandi/xenlight_exporter/pkg/collectors"
```

2021-06-23 12:32 UTC, nlewo approved these changes
Thanks @cavus700 !

2021-06-23 14:26 UTC, merged